// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCos5u6WnoIO0-JRmhFMkGGxc8tXO3_zn4',
    appId: '1:830096374887:web:309f3ed76046c5c27ea8c2',
    messagingSenderId: '830096374887',
    projectId: 'society-53c4b',
    authDomain: 'society-53c4b.firebaseapp.com',
    storageBucket: 'society-53c4b.firebasestorage.app',
    measurementId: 'G-5EM41RMZL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRWfPSAPPl0PpOXOWofY8WeGCpe4KcSy4',
    appId: '1:830096374887:android:96d0aaee810368477ea8c2',
    messagingSenderId: '830096374887',
    projectId: 'society-53c4b',
    storageBucket: 'society-53c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLYB8btbTNrYfmxY2uny0jNJ74A5S_L0',
    appId: '1:830096374887:ios:83980f5b9dc3a4f07ea8c2',
    messagingSenderId: '830096374887',
    projectId: 'society-53c4b',
    storageBucket: 'society-53c4b.firebasestorage.app',
    iosBundleId: 'com.example.societycart',
  );
}
